spring:
  datasource:
    url: jdbc:h2:mem:cafe
    username: santa
    #password: santa1!
    initialization-mode: always
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true